# Generated by Django 5.2.14 on 2026-05-13 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0002_alter_user_managers_alter_user_username'),
        ('assignments', '0001_initial'),
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'En progreso'), ('passed', 'Aprobada'), ('failed', 'Reprobada'), ('dropped', 'Baja')], default='in_progress', max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_history', to='academics.academicperiod')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_history', to='accounts.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_history', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Historial académico',
                'verbose_name_plural': 'Historial académico',
                'db_table': 'academic_history',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'subject', 'academic_period')},
            },
        ),
        migrations.CreateModel(
            name='GradeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('feedback', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_records', to='assignments.assignment')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='graded_records', to='accounts.teacherprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_records', to='accounts.studentprofile')),
                ('submission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grade_record', to='assignments.submission')),
                ('virtual_classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_records', to='classrooms.virtualclassroom')),
            ],
            options={
                'verbose_name': 'Registro de calificación',
                'verbose_name_plural': 'Registros de calificaciones',
                'db_table': 'grade_records',
                'ordering': ['-graded_at', '-created_at'],
                'unique_together': {('student', 'virtual_classroom', 'assignment')},
            },
        ),
    ]
