# Generated by Django 5.2.14 on 2026-07-21 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklymodule',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='classrooms/modules/videos/'),
        ),
        migrations.AddField(
            model_name='weeklymodule',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
