# Generated by Django 5.2.14 on 2026-07-22 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_weeklymodule_video_file_weeklymodule_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionPrecheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('has_title', models.BooleanField(default=False)),
                ('has_conclusion', models.BooleanField(default=False)),
                ('has_bibliography', models.BooleanField(default=False)),
                ('paragraph_count', models.PositiveIntegerField(default=0)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('score', models.PositiveIntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True)),
                ('source_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prechecks', to='assignments.submissionfile')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='precheck', to='assignments.submission')),
            ],
            options={
                'verbose_name': 'Prevalidación de entrega',
                'verbose_name_plural': 'Prevalidaciones de entregas',
                'db_table': 'submission_prechecks',
            },
        ),
    ]
