# Generated by Django 5.2.14 on 2026-05-12 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0002_alter_user_managers_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualClassroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('max_students', models.PositiveIntegerField(default=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo'), ('closed', 'Cerrado'), ('cancelled', 'Cancelado')], default='draft', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='virtual_classrooms', to='academics.academicperiod')),
                ('main_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_classrooms', to='accounts.teacherprofile')),
                ('study_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='virtual_classrooms', to='academics.studyplan')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='virtual_classrooms', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Salón virtual',
                'verbose_name_plural': 'Salones virtuales',
                'db_table': 'virtual_classrooms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_in_class', models.CharField(choices=[('main', 'Profesor titular'), ('assistant', 'Asistente'), ('reviewer', 'Revisor')], default='main', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classroom_assignments', to='accounts.teacherprofile')),
                ('virtual_classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='classrooms.virtualclassroom')),
            ],
            options={
                'verbose_name': 'Asignación de profesor',
                'verbose_name_plural': 'Asignaciones de profesores',
                'db_table': 'teacher_assignments',
                'unique_together': {('teacher', 'virtual_classroom')},
            },
        ),
        migrations.CreateModel(
            name='ClassroomEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('dropped', 'Baja'), ('completed', 'Completado')], default='active', max_length=20)),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classroom_enrollments', to='accounts.studentprofile')),
                ('virtual_classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='classrooms.virtualclassroom')),
            ],
            options={
                'verbose_name': 'Inscripción a salón virtual',
                'verbose_name_plural': 'Inscripciones a salones virtuales',
                'db_table': 'classroom_enrollments',
                'unique_together': {('student', 'virtual_classroom')},
            },
        ),
    ]
