# Generated by Django 5.2.14 on 2026-05-14 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0002_alter_user_managers_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('enrollment', 'Inscripción'), ('tuition', 'Colegiatura'), ('exam', 'Examen'), ('penalty', 'Recargo'), ('other', 'Otro')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('default_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Concepto de cobro',
                'verbose_name_plural': 'Conceptos de cobro',
                'db_table': 'finance_charge_concepts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('partial', 'Parcial'), ('paid', 'Pagado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('academic_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_charges', to='academics.academicperiod')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_charges', to='finance.chargeconcept')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Cargo al alumno',
                'verbose_name_plural': 'Cargos a alumnos',
                'db_table': 'finance_student_charges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta'), ('transfer', 'Transferencia'), ('online', 'Pago en línea'), ('other', 'Otro')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], default='completed', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.studentcharge')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Pago de alumno',
                'verbose_name_plural': 'Pagos de alumnos',
                'db_table': 'finance_student_payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
