# Generated by Django 5.2.14 on 2026-05-12 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('enrollment_start', models.DateField()),
                ('enrollment_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo'), ('closed', 'Cerrado')], default='draft', max_length=20)),
            ],
            options={
                'verbose_name': 'Periodo académico',
                'verbose_name_plural': 'Periodos académicos',
                'db_table': 'academic_periods',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('duration_months', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'db_table': 'careers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('credits', models.PositiveIntegerField(default=0)),
                ('weekly_hours', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'db_table': 'subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('effective_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='study_plans', to='academics.career')),
            ],
            options={
                'verbose_name': 'Plan de estudios',
                'verbose_name_plural': 'Planes de estudio',
                'db_table': 'study_plans',
                'ordering': ['career__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudyPlanSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle_number', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=1)),
                ('mandatory', models.BooleanField(default=True)),
                ('passing_grade', models.DecimalField(decimal_places=2, default=70.0, max_digits=5)),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_subjects', to='academics.studyplan')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_plans', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Materia por plan',
                'verbose_name_plural': 'Materias por plan',
                'db_table': 'study_plan_subjects',
                'ordering': ['study_plan', 'cycle_number', 'order'],
                'unique_together': {('study_plan', 'subject')},
            },
        ),
    ]
